apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: for-hpa-api-hpa
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: for-hpa-api-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageValue: 50m # 50 millicpu = 0.05 cpu
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageValue: 50m # 50 millicpu = 0.05 cpu

