apiVersion: apps/v1
kind: Deployment
metadata:
  name: for-hpa-api-deployment
spec:
  selector:
    matchLabels:
      app: for-hpa-api
  template:
    metadata:
      labels:
        app: for-hpa-api
    spec:
      containers:
        - name: for-hpa-api
          image: prabhudev/febtraining2025:for-hpa-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m # 100 millicpu = 0.1 cpu
              memory: 100Mi # 100 MB
            limits:
              cpu: 200m # 200 millicpu = 0.2 cpu
              memory: 200Mi # 200 MB
---
apiVersion: v1
kind: Service
metadata:
  name: for-hpa-api-service
spec:
  selector:
    app: for-hpa-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
  type: NodePort
