apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-deployment
  labels:
    app: rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
        - name: rest-api
          image: prabhudev/febtraining2025:api-for-k8s
          env:
            - name: WELCOME
              value: "Welcome to the Kubernetes world"
            - name: greetings
              valueFrom:
                configMapKeyRef:
                  name: training-config
                  key: greetings
          ports:
            - containerPort: 8080
