# kubectl create deployment rest-api-deployment --image=rest-api-for-k8s:latest --replicas=1 -ns=spring-k8s-ns
apiVersion: v1
kind: Namespace
metadata:
  name: spring-k8s-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-deployment
  namespace: spring-k8s-ns
  labels:
    app: rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
      - name: rest-api
        image: prabhudev/febtraining2025:api-for-k8s
        ports:
        - containerPort: 8080