apiVersion: apps/v1
kind: Deployment
metadata:
  name: cube-api
  labels:
    app: cube-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cube-api
  template:
    metadata:
      labels:
        app: cube-api
    spec:
      containers:
        - name: cube-api
          image: prabhudev/febtraining2025:cube-api
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cube-api
spec:
  selector:
    app: cube-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cube-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /cube/$1
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /math/cube/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cube-api
                port:
                  number: 80













