apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-services-api
  labels:
    app: k8s-services-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-services-api
  template:
    metadata:
      labels:
        app: k8s-services-api
    spec:
      containers:
        - name: k8s-services-api
          image: prabhudev/febtraining2025:k8s-services-api
          ports:
            - containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-services-api
spec:
  selector:
    app: k8s-services-api
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
