# stage1
FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /app
COPY . /app
RUN ./mvnw clean compile package -DskipTests

# stage2
FROM eclipse-temurin:21.0.6_7-jre-ubi9-minimal
WORKDIR /app
COPY --FROM=builder /app/target/for-multistage-builds-api-0.0.1.jar app.jar
CMD ["java", "-jar", "app.jar"]